site_name: Portal do Conhecimento

theme:
  name: material
  language: pt-BR
  palette:
    # Modo Dark
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Modo claro
      accent: deep purple

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Modo noturno
      accent: deep orange

  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - toc.integrate
    - navigation.top
    - navigation.indexes
    # - navigation.expand
    - search.suggest
    - search.highlight

# Bloco de codigo
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # Habilitar bloco de sanfona


  - admonition
  - pymdownx.details
  - attr_list

# nav:
#   - Início: index.md
